name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels:
  - "🐛 Bug"
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Backend Infomation (for Server Admins):"
      description: |
        example:
          - Python: 3.12 
          - PostgreSQL: 16
          - Redis: 7
          - OS: Ubuntu 22.04
          - Architecture: x64
      value: |
        - Python: 
        - PostgreSQL: 
        - Redis: 
        - OS: 
        - Architecture: 
    validations:
      required: false

  - type: textarea
    attributes:
      label: Client Infomation
      description: |
        example:
          - OS: Windows10 22H2
          - Device: Dell XPS8940
          - Browser: Google Chrome 126.0.6478.185
          - Server URL: https://example.com
          - Backend Version: 0.1.0
      value: |
        - OS: 
        - Device: 
        - Browser: 
        - Server URL: 
        - Backend Version: 
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: checkboxes
    id: self-fix
    attributes:
      label: Would you like to fix this bug yourself?
      options:
        - label: Yes, I will fix this bug myself and send a pull request
          required: false
