name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE REQUEST] "
labels:
  - "✨️ Feature"
body:
  - type: textarea
    attributes:
      label: "summary"
      description: ""
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: checkboxes
    id: self-implement
    attributes:
      label: Would you like to implement this feature request yourself?
      options:
        - label: Yes, I will implement this feature myself and send a pull request
          required: true
